### PR TITLE
Allow specifying prop name and display name with InjectFalcorModel

### PR DESCRIPTION
**Pull request by emilgoldsmith**

### CODE REVIEW

**Comment by ratson** [comment]
@emilgoldsmith Thanks for the PR. Would you add a simple test case for this?

**Comment by emilgoldsmith** [comment]
Sure thing! I'm going to be using this in my project as I really like the API so think I'll be submitting a few more PRs including one for documentation :), some of them may be more opinionated so feel free to disagree

**Comment by ratson** [comment]
Contributing to documentation is always welcome :)

**Comment by emilgoldsmith** [comment]
pushed changes :). I also like how you allow building the display name for other components so added that functionality here as well and added tests for all that

**Pull request merged**
